### PR TITLE
Add tests and wheel for Python 3.12

### PR DESCRIPTION
**Pull request by StephenOman**
Gymnasium v1.0.0 supports Python 3.12, so this PR adds that Python version to the test matrix & includes a wheel on release build.

### CODE REVIEW

**Review by heiner — COMMENTED** [review]
Change _looks_ good but I'm unsure why this test is unhappy:

```
ls: cannot access 'dist/*311*manylinux*x86_64*.whl': No such file or directory
```

**Comment by StephenOman** [comment]
Oh I think I know what that is. I bumped up the version of the wheel generated to 3.12. However, the later wheel test is looking for the 3.11 version, which is no longer generated during the run.

**Comment by heiner** [comment]
Python's build system ecosystem is (1) kinda broken, and (2) in flux. It looks like we need to add a dependency on setuptools for 3.12 somewhere?

I'd be interested in reconsidering how we build NLE and switch to `uv`, but I'm a bit short on time these days. Thanks for your amazing work @StephenOman btw!

**Comment by StephenOman** [comment]
As per the [release notes for Python 3.12](https://docs.python.org/3/whatsnew/3.12.html), `setuptools` is no longer installed by default in Python virtual environments. So it has to be installed explicitly in the virtual environment preparation. It's not necessary for the earlier versions of Python, but I've added it to all the virtual environments for consistency.

**Review by heiner — APPROVED** [review]
Very nice, thanks!

**Comment by StephenOman** [comment]
This PR addresses issue #39

**Pull request merged**
