### PR TITLE
Nethack 3.6.7 patch only

### PR DESCRIPTION
**Pull request by StephenOman**
This PR is focused on pulling in the changed files in [NetHack 3.6.7 Released](https://github.com/NetHack/NetHack/releases/tag/NetHack-3.6.7_Released) and reapplying the NLE-only changes (which are invisible in the file comparison below).

Several files have been deleted from NetHack, a few new ones have been added. One NLE test needed minor modification.

Also removed the requirement for Facebook Contributor License Agreement.

### CODE REVIEW

**Review by heiner — APPROVED** [review]
Awesome, thank you!

So no changes to the cmake files required?

**Comment by StephenOman** [comment]
Not that I could see. 😀 

There was a fair bit of preparation work in this. I was experimenting in the other upgrade branch with some ideas to make it easier to upgrade over time. I'll put them into some other PRs so you can review and see what you think.

**Comment by heiner** [comment]
One thing that I personally like but that might be too annoying is actually merging upstream [NetHack](https://github.com/NetHack/NetHack), i.e., having their commits in our commit history. One can do that in various ways (cherry-picking, git merge, git rebase onto?) but I understand if that's too involved.

**Comment by StephenOman** [comment]
We could look at moving the core NetHack files into a GitHub Subtree of NLE. That way we can pull upstream changes and merge them, retaining the NLE specific changes. Would need a bit of change to the CMake setup.

**Comment by heiner** [comment]
I think that wouldn't work well with the changes we have to make in NetHack core files, of which there are a few. Just the commits from upstream NetHack would be good. You could probably get that by going to current main, merging upstream nethack with `-X theirs` and then applying whatever diff moves you to the state of the branch in this PR.

**Pull request merged**
